/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/auth/register": {
    /** ユーザ登録 */
    post: operations["AuthController_register"];
  };
  "/auth/login": {
    /** ログイン */
    post: operations["AuthController_login"];
  };
  "/post": {
    /** 投稿一覧取得 */
    get: operations["PostController_findAll"];
    /** 投稿 */
    post: operations["PostController_create"];
  };
  "/post/{name}": {
    /** ユーザの投稿一覧取得 */
    get: operations["PostController_findByUser"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    RegisterRequest: {
      /** @example test */
      name: string;
      /** @example password */
      password: string;
    };
    BadRequest: {
      /**
       * @example [
       *   "* should not be empty"
       * ]
       */
      message: string[];
      /** @example Bad Request */
      error: string;
      /** @example 400 */
      statusCode: number;
    };
    Conflict: {
      /** @example Conflict */
      message: string;
      /** @example 409 */
      statusCode: number;
    };
    InternalServerError: {
      /** @example Internal Server Error */
      message: string;
      /** @example 500 */
      statusCode: number;
    };
    LoginResponce: {
      /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsIm5hbWUiOiJ0ZXN0IiwiaWF0IjoxNjkxOTA0NTQ0fQ.I0ShA2nC81q2i8rscX8W_EkrKqxvb1Jqgl_I72j9PBM */
      token: string;
    };
    Unauthorized: {
      /** @example Unauthorized */
      message: string;
      /** @example 401 */
      statusCode: number;
    };
    CreateRequest: {
      /** @example Hello! */
      content: string;
    };
    User: {
      /** @example 1 */
      id: number;
      /** @example test */
      name: string;
    };
    FindAllResponce: {
      /** @example 1 */
      id: number;
      /** @example Hello! */
      content: string;
      /**
       * Format: date-time
       * @example 2021-01-01T00:00:00.000Z
       */
      createdAt: string;
      user: components["schemas"]["User"];
    };
    NotFound: {
      /** @example Not Found */
      message: string;
      /** @example 404 */
      statusCode: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** ユーザ登録 */
  AuthController_register: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: never;
      };
      /** @description BadRequest */
      400: {
        content: {
          "application/json": components["schemas"]["BadRequest"];
        };
      };
      /** @description Conflict */
      401: {
        content: {
          "application/json": components["schemas"]["Conflict"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["InternalServerError"];
        };
      };
    };
  };
  /** ログイン */
  AuthController_login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["LoginResponce"];
        };
      };
      /** @description BadRequest */
      400: {
        content: {
          "application/json": components["schemas"]["BadRequest"];
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/json": components["schemas"]["Unauthorized"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["InternalServerError"];
        };
      };
    };
  };
  /** 投稿一覧取得 */
  PostController_findAll: {
    parameters: {
      query: {
        page: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["FindAllResponce"][];
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/json": components["schemas"]["Unauthorized"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["InternalServerError"];
        };
      };
    };
  };
  /** 投稿 */
  PostController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: never;
      };
      /** @description BadRequest */
      400: {
        content: {
          "application/json": components["schemas"]["BadRequest"];
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/json": components["schemas"]["Unauthorized"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["InternalServerError"];
        };
      };
    };
  };
  /** ユーザの投稿一覧取得 */
  PostController_findByUser: {
    parameters: {
      query: {
        page: number;
      };
      path: {
        /**
         * @description ユーザ名
         * @example test
         */
        name: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["FindAllResponce"][];
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/json": components["schemas"]["Unauthorized"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["NotFound"];
        };
      };
      /** @description Internal server error */
      500: {
        content: {
          "application/json": components["schemas"]["InternalServerError"];
        };
      };
    };
  };
}
